// assistantEngine.js — Matching engine for the AI Playground Assistant
import { PLAYGROUND_KB, FOLLOWUPS } from './AssistantKB.js'

export function generateAssistantResponse(message, lang = 'en') {
  const lower = message.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '') // remove accents
    .trim()

  // Greetings
  if (/^(hola|hello|hi|hey|buenos|buenas|que tal|good morning|good afternoon|saludos|sup|yo)/.test(lower)) {
    return greeting(lang)
  }

  // Thanks
  if (/^(thanks|gracias|thank you|merci|thx|ty)/.test(lower)) {
    return thanks(lang)
  }

  // Help
  if (/^(help|ayuda|menu|opciones|que puedo preguntar|commands|comandos|\?)/.test(lower)) {
    return helpMenu(lang)
  }

  // Surprise/random question
  if (/^(surprise|sorpresa|random|algo interesante|fun fact|dato curioso|sorprendeme|surprise me)/.test(lower)) {
    return randomTopic(lang)
  }

  // Score all topics
  const scores = Object.entries(PLAYGROUND_KB).map(([key, topic]) => {
    let score = 0
    for (const pattern of topic.question_patterns) {
      const patLower = pattern.toLowerCase()
        .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
      if (lower.includes(patLower)) {
        score += patLower.split(' ').length * 2
      }
      // Also check individual word overlap for partial matches
      const patWords = patLower.split(/\s+/)
      for (const w of patWords) {
        if (w.length > 3 && lower.includes(w)) {
          score += 1
        }
      }
    }
    return { key, topic, score }
  }).filter(s => s.score > 0).sort((a, b) => b.score - a.score)

  if (scores.length > 0) {
    const best = scores[0]
    return {
      text: lang === 'es' ? best.topic.answer_es : best.topic.answer_en,
      topic: best.key,
      confidence: Math.min(0.95, best.score * 0.15),
      suggestedFollowups: getFollowups(best.key, lang),
      mode: 'knowledge'
    }
  }

  // Agentic mode for open-ended questions
  if (lower.length > 30) {
    return agenticResponse(message, lang)
  }

  return fallback(lang)
}

function agenticResponse(message, lang) {
  const lower = message.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')

  const hasWhy = /why|por que|porque/.test(lower)
  const hasHow = /how|como|de que manera/.test(lower)
  const hasCompare = /compare|vs|versus|diferencia|mejor/.test(lower)

  let reasoning = ''
  if (hasWhy) {
    reasoning = lang === 'es'
      ? '**Modo Agente — Razonamiento profundo:**\n\nAnalizando tu pregunta "por que"...\n\n'
      : '**Agentic Mode — Deep Reasoning:**\n\nAnalyzing your "why" question...\n\n'
  } else if (hasHow) {
    reasoning = lang === 'es'
      ? '**Modo Agente — Analisis paso a paso:**\n\n'
      : '**Agentic Mode — Step-by-step Analysis:**\n\n'
  } else if (hasCompare) {
    reasoning = lang === 'es'
      ? '**Modo Agente — Analisis comparativo:**\n\n'
      : '**Agentic Mode — Comparative Analysis:**\n\n'
  } else {
    reasoning = lang === 'es'
      ? '**Modo Agente — Exploracion abierta:**\n\n'
      : '**Agentic Mode — Open Exploration:**\n\n'
  }

  // Search KB for related topics and synthesize
  const related = findRelatedTopics(message, 3)
  if (related.length > 0) {
    const context = related.map(r => lang === 'es' ? r.topic.answer_es : r.topic.answer_en).join('\n\n')
    reasoning += context
    reasoning += lang === 'es'
      ? '\n\n---\n*Respuesta generada combinando conocimiento de multiples temas.*'
      : '\n\n---\n*Response generated by combining knowledge from multiple topics.*'
  } else {
    reasoning += lang === 'es'
      ? 'Esta es una pregunta interesante que va mas alla de los temas predefinidos. En un entorno de produccion, esto se procesaria con un LLM como Llama 3.3 70B para darte una respuesta completa y contextualizada.'
      : 'This is an interesting question that goes beyond predefined topics. In production, this would be processed by an LLM like Llama 3.3 70B for a complete, contextualized response.'
  }

  return {
    text: reasoning,
    topic: 'agentic',
    confidence: 0.7,
    suggestedFollowups: lang === 'es'
      ? ['Que mas puedo preguntar?', 'Ayuda', 'Sorpresa']
      : ['What else can I ask?', 'Help', 'Surprise'],
    mode: 'agentic'
  }
}

function findRelatedTopics(message, topK) {
  const lower = message.toLowerCase()
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
  return Object.entries(PLAYGROUND_KB)
    .map(([key, topic]) => {
      let score = 0
      for (const p of topic.question_patterns) {
        const words = p.toLowerCase()
          .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
          .split(' ')
        for (const w of words) {
          if (w.length > 3 && lower.includes(w)) score++
        }
      }
      return { key, topic, score }
    })
    .filter(s => s.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, topK)
}

function greeting(lang) {
  return {
    text: lang === 'es'
      ? 'Hola! Soy el asistente de AI Playground. Puedo ayudarte con cualquier pregunta sobre las 7 funciones de IA: Chat, Analisis, P&R, Generacion, Extraccion, Traduccion y Comparacion de Modelos. Que te gustaria saber?'
      : 'Hello! I\'m the AI Playground assistant. I can help you with any question about the 7 AI features: Chat, Analysis, Q&A, Generation, Extraction, Translation, and Model Comparison. What would you like to know?',
    topic: 'greeting',
    confidence: 1,
    suggestedFollowups: lang === 'es'
      ? ['Que es esto?', 'Mostrar funciones', 'Como empiezo?', 'Sorpresa']
      : ['What is this?', 'Show features', 'How do I start?', 'Surprise'],
    mode: 'knowledge'
  }
}

function thanks(lang) {
  return {
    text: lang === 'es'
      ? 'De nada! Si tienes mas preguntas sobre AI Playground, no dudes en preguntar. Estoy aqui para ayudarte.'
      : 'You\'re welcome! If you have more questions about AI Playground, don\'t hesitate to ask. I\'m here to help.',
    topic: 'thanks',
    confidence: 1,
    suggestedFollowups: lang === 'es'
      ? ['Que mas puedo hacer?', 'Mejor funcion?', 'Sorpresa']
      : ['What else can I do?', 'Best feature?', 'Surprise'],
    mode: 'knowledge'
  }
}

function helpMenu(lang) {
  const en = `**Here's what you can ask me about:**

**Features:**
- "What is AI Playground?" — Overview
- "How does Chat work?" — Chat feature
- "Tell me about Analysis" — Document analysis
- "What is RAG?" — Q&A pipeline
- "How does Generate work?" — Content creation
- "What can Extract do?" — Data extraction
- "Translation languages?" — Translation
- "Compare models" — Model comparison

**Technical:**
- "Tech stack?" — Technologies used
- "Model pricing?" — Cost per token
- "Privacy?" — Data handling
- "Architecture?" — System design

**Fun:**
- "Best feature?" — My recommendation
- "Surprise!" — Random topic
- "Easter egg" — Hidden features
- "Future features?" — What's coming next

*Or just ask anything in English or Spanish!*`

  const es = `**Esto es lo que puedes preguntarme:**

**Funciones:**
- "Que es AI Playground?" — Vista general
- "Como funciona el Chat?" — Funcion de chat
- "Cuentame del Analisis" — Analisis de documentos
- "Que es RAG?" — Pipeline de P&R
- "Como funciona Generar?" — Creacion de contenido
- "Que puede Extraer?" — Extraccion de datos
- "Idiomas de traduccion?" — Traduccion
- "Comparar modelos" — Comparacion de modelos

**Tecnico:**
- "Stack tecnologico?" — Tecnologias usadas
- "Precios de modelos?" — Costo por token
- "Privacidad?" — Manejo de datos
- "Arquitectura?" — Diseno del sistema

**Divertido:**
- "Mejor funcion?" — Mi recomendacion
- "Sorpresa!" — Tema aleatorio
- "Easter egg" — Funciones ocultas
- "Funciones futuras?" — Que viene proximamente

*O simplemente pregunta lo que quieras en ingles o espanol!*`

  return {
    text: lang === 'es' ? es : en,
    topic: 'help',
    confidence: 1,
    suggestedFollowups: lang === 'es'
      ? ['Que es esto?', 'Mejor funcion?', 'Sorpresa', 'Stack tecnologico?']
      : ['What is this?', 'Best feature?', 'Surprise', 'Tech stack?'],
    mode: 'knowledge'
  }
}

function randomTopic(lang) {
  const keys = Object.keys(PLAYGROUND_KB)
  const funKeys = ['easter_egg', 'best_feature', 'compare_playground_vs_chatgpt', 'future_features', 'groq_api', 'performance', 'use_cases']
  const pool = funKeys.filter(k => keys.includes(k))
  const key = pool[Math.floor(Math.random() * pool.length)]
  const topic = PLAYGROUND_KB[key]
  return {
    text: lang === 'es' ? topic.answer_es : topic.answer_en,
    topic: key,
    confidence: 0.9,
    suggestedFollowups: getFollowups(key, lang),
    mode: 'knowledge'
  }
}

function fallback(lang) {
  return {
    text: lang === 'es'
      ? 'No estoy seguro de entender tu pregunta. Intenta preguntar sobre alguna funcion especifica como "Que es el analisis?", "Como funciona RAG?", o "Comparar modelos". Escribe **ayuda** para ver todos los temas disponibles.'
      : 'I\'m not sure I understand your question. Try asking about a specific feature like "What is analysis?", "How does RAG work?", or "Compare models". Type **help** to see all available topics.',
    topic: 'fallback',
    confidence: 0,
    suggestedFollowups: lang === 'es'
      ? ['Ayuda', 'Que es esto?', 'Funciones', 'Sorpresa']
      : ['Help', 'What is this?', 'Features', 'Surprise'],
    mode: 'knowledge'
  }
}

function getFollowups(topicKey, lang) {
  const fu = FOLLOWUPS[topicKey]
  if (fu) return lang === 'es' ? fu.es : fu.en
  return lang === 'es'
    ? ['Ayuda', 'Todas las funciones', 'Sorpresa']
    : ['Help', 'All features', 'Surprise']
}
